# Generated by Django 2.1.12 on 2020-03-02 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssl',
            old_name='validation',
            new_name='validation_type',
        ),
    ]
