# Generated by Django 2.1 on 2020-03-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_price', '0004_ssl_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssl',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
    ]
