# Generated by Django 2.1 on 2020-03-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_price', '0005_auto_20200304_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssl',
            name='price',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
