# Generated by Django 2.1 on 2020-03-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_price', '0007_auto_20200304_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssl',
            name='price',
            field=models.FloatField(),
        ),
    ]
