# Generated by Django 2.1 on 2020-03-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_price', '0009_auto_20200304_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssl',
            name='price',
            field=models.IntegerField(),
        ),
    ]
