# Generated by Django 2.1 on 2020-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0002_vps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vps',
            name='ram',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
