# Generated by Django 2.1 on 2020-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0003_auto_20200305_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='vps',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
