# Generated by Django 3.0.3 on 2020-02-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='renew_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='domain',
            name='trans_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8),
        ),
    ]
