# Generated by Django 3.0.3 on 2020-02-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_price', '0003_auto_20200220_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='usd',
            new_name='reg_origin_usd',
        ),
        migrations.AddField(
            model_name='domain',
            name='rates',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='domain',
            name='reg_promotion_usd',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='domain',
            name='renew_price_usd',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_location',
            field=models.CharField(choices=[('FOR', 'Foreign'), ('VN', 'VietNam')], default='VN', max_length=10),
        ),
    ]
