# Generated by Django 3.0.3 on 2020-02-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_price', '0005_domain_trans_price_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='rates',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reg_origin',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reg_origin_usd',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reg_promotion',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reg_promotion_usd',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='renew_price',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='renew_price_usd',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='trans_price',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='trans_price_usd',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
