# Generated by Django 3.0.3 on 2020-02-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_price', '0006_auto_20200222_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='rates',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
