# Generated by Django 3.0.3 on 2020-02-23 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_price', '0007_auto_20200222_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='rates',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='reg_origin',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='reg_origin_usd',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='reg_promotion',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='reg_promotion_usd',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='renew_price',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='renew_price_usd',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='trans_price',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='trans_price_usd',
        ),
    ]
