# Generated by Django 3.0.3 on 2020-02-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_price', '0008_auto_20200223_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='rates',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='domain',
            name='reg_origin',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=8),
        ),
        migrations.AddField(
            model_name='domain',
            name='reg_origin_usd',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='domain',
            name='reg_promotion',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=8),
        ),
        migrations.AddField(
            model_name='domain',
            name='reg_promotion_usd',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='domain',
            name='renew_price',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=8),
        ),
        migrations.AddField(
            model_name='domain',
            name='renew_price_usd',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='domain',
            name='trans_price',
            field=models.DecimalField(decimal_places=3, default='0', max_digits=8),
        ),
        migrations.AddField(
            model_name='domain',
            name='trans_price_usd',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
