# Generated by Django 3.0.3 on 2020-02-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_price', '0009_auto_20200223_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='reg_origin',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reg_promotion',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='renew_price',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='trans_price',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True),
        ),
    ]
