# Generated by Django 2.1 on 2020-03-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_price', '0010_auto_20200223_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='reg_origin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='reg_promotion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='renew_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='trans_price',
            field=models.IntegerField(null=True),
        ),
    ]
